from pathlib import Path


def command_status(args="", state=None, runtime=None):
    project = getattr(state, "active_project", "unknown")
    return f"policy plugin active | project={project}"


def on_project_created(context=None, plugin=""):
    data = dict(context or {})
    root = Path(str(data.get("project_root", "")).strip())
    if not root:
        return {"action": "continue"}

    readme = root / "README.md"
    if not readme.exists():
        readme.write_text(
            f"# {data.get('project_name', root.name)}\n\nGenerated by {plugin}.\n",
            encoding="utf-8",
        )
        return {"action": "warn", "message": f"{plugin}: created README.md"}
    return {"action": "continue"}


def before_task(context=None, plugin=""):
    data = dict(context or {})
    text = str(data.get("user_input", "")).strip()

    banned = ["delete all files", "format c:"]
    if any(item in text.lower() for item in banned):
        return {"action": "block", "reason": f"{plugin}: blocked unsafe request"}

    if text.startswith("!"):
        return {"action": "mutate", "updates": {"user_input": text[1:].strip()}}

    if not text:
        return {"action": "warn", "message": f"{plugin}: empty task"}
    return {"action": "continue"}


def after_task(context=None, plugin=""):
    data = dict(context or {})
    project = str(data.get("active_project", "unknown")).strip() or "unknown"
    task_id = str(data.get("task_id", "n/a")).strip() or "n/a"
    result = str(data.get("result", ""))

    log_dir = Path("workspace") / project / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    line = f"{task_id}|chars={len(result)}\n"
    with (log_dir / "task_summary.log").open("a", encoding="utf-8") as fh:
        fh.write(line)
    return {"action": "continue"}
